// DocumentScannerModule.java

package com.docscanner;

import android.Manifest;
import android.app.Activity;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.graphics.Bitmap;
import android.location.Location;
import android.net.Uri;
import android.os.Build;
import android.os.Looper;
import android.os.SystemClock;
import android.util.Base64;
import android.util.Log;

import androidx.core.app.ActivityCompat;
import androidx.core.content.ContextCompat;
import androidx.exifinterface.media.ExifInterface;

import com.facebook.react.bridge.ActivityEventListener;
import com.facebook.react.bridge.BaseActivityEventListener;
import com.facebook.react.bridge.Callback;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.bridge.WritableArray;
import com.facebook.react.bridge.WritableMap;
import com.facebook.react.bridge.WritableNativeArray;
import com.facebook.react.bridge.WritableNativeMap;
import com.facebook.react.modules.core.PermissionAwareActivity;

import com.google.android.gms.location.FusedLocationProviderClient;
import com.google.android.gms.location.LocationCallback;
import com.google.android.gms.location.LocationRequest;
import com.google.android.gms.location.LocationResult;
import com.google.android.gms.location.LocationServices;
import com.google.android.gms.location.Priority;

import com.google.mlkit.vision.documentscanner.GmsDocumentScanner;
import com.google.mlkit.vision.documentscanner.GmsDocumentScannerOptions;
import com.google.mlkit.vision.documentscanner.GmsDocumentScanning;
import com.google.mlkit.vision.documentscanner.GmsDocumentScanningResult;

import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.TimeZone;
import java.util.UUID;

// For New Architecture: extend the generated spec base class
// This class is generated by React Native Codegen based on src/NativeDocumentScanner.ts
// and will be available when newArchEnabled=true
@SuppressWarnings("KotlinInternalInJava")
public class DocumentScannerModule extends com.docscanner.NativeDocumentScannerSpec {

    public static final String NAME = "DocumentScanner";
    private static final String TAG = "DocumentScannerModule";
    private static final int DOCUMENT_SCAN_REQUEST = 1001;
    private static final int LOCATION_PERMISSION_REQUEST = 1002;

    private final ReactApplicationContext reactContext;
    private Callback scannerCallback;
    private ReadableMap scannerOptions;
    private Location currentLocation;
    // Target accuracy (metres) for the current scan: location updates stop
    // once a fix this good arrives, or when the scanner closes.
    private float targetAccuracy;
    private FusedLocationProviderClient locationClient;
    private LocationCallback locationCallback;

    // A cached fix older than this is not used to seed the scan.
    private static final long MAX_CACHED_LOCATION_AGE_MS = 5 * 60 * 1000;

    private final ActivityEventListener activityEventListener = new BaseActivityEventListener() {
        @Override
        public void onActivityResult(Activity activity, int requestCode, int resultCode, Intent data) {
            if (requestCode == DOCUMENT_SCAN_REQUEST) {
                handleScanResult(resultCode, data);
            }
        }
    };

    public DocumentScannerModule(ReactApplicationContext reactContext) {
        super(reactContext);
        this.reactContext = reactContext;
        reactContext.addActivityEventListener(activityEventListener);
    }

    @Override
    public String getName() {
        return NAME;
    }

    @ReactMethod
    @Override
    public void launchScanner(ReadableMap options, Callback callback) {
        Activity currentActivity = getCurrentActivity();

        if (currentActivity == null) {
            WritableMap errorResponse = new WritableNativeMap();
            errorResponse.putBoolean("error", true);
            errorResponse.putString("errorMessage", "Activity doesn't exist");
            callback.invoke(errorResponse);
            return;
        }

        scannerCallback = callback;
        scannerOptions = options;
        currentLocation = null;

        boolean includeLocationExif = options.hasKey("includeLocationExif") && options.getBoolean("includeLocationExif");

        if (includeLocationExif) {
            fetchLocationThenScan(currentActivity);
        } else {
            startScanner(currentActivity);
        }
    }

    /**
     * Location is best-effort and never delays the camera: at most we wait
     * for the user's answer to a permission prompt, never for a fix.
     */
    private void fetchLocationThenScan(Activity activity) {
        String level = locationAccuracyLevel();
        targetAccuracy = targetAccuracyForLevel(level);
        boolean needsPrecise = !"approximate".equals(level);

        if (hasRequiredPermission(activity, needsPrecise)
                || !mayRequestPermission()
                || !(activity instanceof PermissionAwareActivity)) {
            // Either nothing to ask, or we may not ask: use whatever is
            // granted (possibly nothing) and open the camera immediately.
            startLocationCapture(activity);
            startScanner(activity);
            return;
        }

        // Ask for exactly the tier the level needs. Android 12+ requires
        // COARSE alongside FINE. The OS itself suppresses the dialog once the
        // user has permanently denied it. The camera opens after the answer.
        String[] permissions = needsPrecise
                ? new String[]{Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION}
                : new String[]{Manifest.permission.ACCESS_COARSE_LOCATION};
        ((PermissionAwareActivity) activity).requestPermissions(permissions, LOCATION_PERMISSION_REQUEST,
                (requestCode, perms, grantResults) -> {
                    if (requestCode != LOCATION_PERMISSION_REQUEST) return false;
                    startLocationCapture(activity);
                    startScanner(activity);
                    return true;
                });
    }

    private String locationAccuracyLevel() {
        if (scannerOptions != null && scannerOptions.hasKey("locationAccuracy")) {
            String level = scannerOptions.getString("locationAccuracy");
            if ("approximate".equals(level) || "balanced".equals(level)) return level;
        }
        return "precise";
    }

    private boolean mayRequestPermission() {
        return scannerOptions == null
                || !scannerOptions.hasKey("requestLocationPermission")
                || scannerOptions.getBoolean("requestLocationPermission");
    }

    private static boolean isGranted(Activity activity, String permission) {
        return ContextCompat.checkSelfPermission(activity, permission) == PackageManager.PERMISSION_GRANTED;
    }

    private static boolean hasRequiredPermission(Activity activity, boolean needsPrecise) {
        if (isGranted(activity, Manifest.permission.ACCESS_FINE_LOCATION)) return true;
        return !needsPrecise && isGranted(activity, Manifest.permission.ACCESS_COARSE_LOCATION);
    }

    private static float targetAccuracyForLevel(String level) {
        if ("approximate".equals(level)) return 3000f;
        if ("balanced".equals(level)) return 100f;
        return 10f;
    }

    private static int priorityForLevel(String level) {
        if ("approximate".equals(level)) return Priority.PRIORITY_LOW_POWER;
        if ("balanced".equals(level)) return Priority.PRIORITY_BALANCED_POWER_ACCURACY;
        return Priority.PRIORITY_HIGH_ACCURACY;
    }

    /**
     * Seed from a recent cached fix, then stream updates in parallel with the
     * scanner, keeping the best fix so far. Whatever we hold when the scan is
     * saved is stamped into the EXIF. No-op without any location permission.
     */
    private void startLocationCapture(Activity activity) {
        if (!isGranted(activity, Manifest.permission.ACCESS_FINE_LOCATION)
                && !isGranted(activity, Manifest.permission.ACCESS_COARSE_LOCATION)) {
            return;
        }
        stopLocationCapture();
        try {
            locationClient = LocationServices.getFusedLocationProviderClient(activity);
            locationClient.getLastLocation()
                    .addOnSuccessListener(location -> {
                        considerLocation(location);
                        // A cached fix that already meets the target ends the search.
                        if (hasTargetFix()) {
                            stopLocationCapture();
                        }
                    })
                    .addOnFailureListener(e -> Log.w(TAG, "getLastLocation failed", e));

            LocationRequest request = new LocationRequest.Builder(priorityForLevel(locationAccuracyLevel()), 1000)
                    .setMinUpdateIntervalMillis(500)
                    .build();
            locationCallback = new LocationCallback() {
                @Override
                public void onLocationResult(LocationResult result) {
                    for (Location location : result.getLocations()) {
                        considerLocation(location);
                    }
                    if (hasTargetFix()) {
                        stopLocationCapture();
                    }
                }
            };
            locationClient.requestLocationUpdates(request, locationCallback, Looper.getMainLooper());
        } catch (SecurityException e) {
            Log.w(TAG, "Location unavailable; proceeding without GPS", e);
        }
    }

    private void stopLocationCapture() {
        if (locationClient != null && locationCallback != null) {
            locationClient.removeLocationUpdates(locationCallback);
        }
        locationCallback = null;
    }

    private static long ageMs(Location location) {
        return (SystemClock.elapsedRealtimeNanos() - location.getElapsedRealtimeNanos()) / 1_000_000;
    }

    private void considerLocation(Location location) {
        if (location == null || !location.hasAccuracy()) return;
        if (ageMs(location) > MAX_CACHED_LOCATION_AGE_MS) return;

        Location current = currentLocation;
        boolean currentIsStale = current != null && ageMs(current) > MAX_CACHED_LOCATION_AGE_MS;
        if (current == null || currentIsStale || location.getAccuracy() <= current.getAccuracy()) {
            currentLocation = location;
        }
    }

    private boolean hasTargetFix() {
        return currentLocation != null && currentLocation.getAccuracy() <= targetAccuracy;
    }

    private void startScanner(Activity activity) {
        // ML Kit scanner settings (Android only). Defaults match the
        // values that were hardcoded before they became configurable.
        int pageLimit = 10;
        if (scannerOptions != null && scannerOptions.hasKey("pageLimit")) {
            pageLimit = Math.max(1, (int) scannerOptions.getDouble("pageLimit"));
        }

        boolean galleryImportAllowed = scannerOptions != null
                && scannerOptions.hasKey("galleryImportAllowed")
                && scannerOptions.getBoolean("galleryImportAllowed");

        int scannerMode = GmsDocumentScannerOptions.SCANNER_MODE_FULL;
        if (scannerOptions != null && scannerOptions.hasKey("scannerMode")) {
            String mode = scannerOptions.getString("scannerMode");
            if ("base".equals(mode)) {
                scannerMode = GmsDocumentScannerOptions.SCANNER_MODE_BASE;
            } else if ("base_with_filter".equals(mode)) {
                scannerMode = GmsDocumentScannerOptions.SCANNER_MODE_BASE_WITH_FILTER;
            }
        }

        // JPEG pages are always produced so `images` keeps working.
        // The PDF is only requested when the caller asks for it.
        GmsDocumentScannerOptions.Builder optionsBuilder = new GmsDocumentScannerOptions.Builder()
                .setGalleryImportAllowed(galleryImportAllowed)
                .setPageLimit(pageLimit)
                .setScannerMode(scannerMode);
        if (includePdf()) {
            optionsBuilder.setResultFormats(
                    GmsDocumentScannerOptions.RESULT_FORMAT_JPEG,
                    GmsDocumentScannerOptions.RESULT_FORMAT_PDF);
        } else {
            optionsBuilder.setResultFormats(GmsDocumentScannerOptions.RESULT_FORMAT_JPEG);
        }

        GmsDocumentScannerOptions scannerOpts = optionsBuilder.build();
        GmsDocumentScanner scanner = GmsDocumentScanning.getClient(scannerOpts);

        scanner.getStartScanIntent(activity)
                .addOnSuccessListener(intentSender -> {
                    try {
                        activity.startIntentSenderForResult(
                                intentSender,
                                DOCUMENT_SCAN_REQUEST,
                                null,
                                0,
                                0,
                                0
                        );
                    } catch (Exception e) {
                        Log.e(TAG, "Error starting scanner", e);
                        WritableMap errorResponse = new WritableNativeMap();
                        errorResponse.putBoolean("error", true);
                        errorResponse.putString("errorMessage", e.getMessage());
                        stopLocationCapture();
                        if (scannerCallback != null) {
                            scannerCallback.invoke(errorResponse);
                            scannerCallback = null;
                        }
                    }
                })
                .addOnFailureListener(e -> {
                    Log.e(TAG, "Error getting scan intent", e);
                    WritableMap errorResponse = new WritableNativeMap();
                    errorResponse.putBoolean("error", true);
                    errorResponse.putString("errorMessage", e.getMessage());
                    stopLocationCapture();
                    if (scannerCallback != null) {
                        scannerCallback.invoke(errorResponse);
                        scannerCallback = null;
                    }
                });
    }

    private void handleScanResult(int resultCode, Intent data) {
        stopLocationCapture();
        if (scannerCallback == null) {
            return;
        }

        if (resultCode == Activity.RESULT_CANCELED) {
            WritableMap response = new WritableNativeMap();
            response.putBoolean("didCancel", true);
            scannerCallback.invoke(response);
            scannerCallback = null;
            return;
        }

        if (resultCode != Activity.RESULT_OK || data == null) {
            WritableMap errorResponse = new WritableNativeMap();
            errorResponse.putBoolean("error", true);
            errorResponse.putString("errorMessage", "Scan failed");
            scannerCallback.invoke(errorResponse);
            scannerCallback = null;
            return;
        }

        GmsDocumentScanningResult result = GmsDocumentScanningResult.fromActivityResultIntent(data);
        if (result == null) {
            WritableMap errorResponse = new WritableNativeMap();
            errorResponse.putBoolean("error", true);
            errorResponse.putString("errorMessage", "Failed to get scan result");
            scannerCallback.invoke(errorResponse);
            scannerCallback = null;
            return;
        }

        WritableArray imagesArray = new WritableNativeArray();

        // Process each scanned page
        GmsDocumentScanningResult.Page[] pages = result.getPages().toArray(new GmsDocumentScanningResult.Page[0]);
        for (GmsDocumentScanningResult.Page page : pages) {
            Uri imageUri = page.getImageUri();
            try {
                WritableMap imageObject = processImage(imageUri);
                if (imageObject != null) {
                    imagesArray.pushMap(imageObject);
                }
            } catch (Exception e) {
                Log.e(TAG, "Error processing image", e);
            }
        }

        WritableMap response = new WritableNativeMap();
        response.putArray("images", imagesArray);

        if (includePdf() && result.getPdf() != null) {
            try {
                WritableMap pdfObject = processPdf(result.getPdf());
                if (pdfObject != null) {
                    response.putMap("pdf", pdfObject);
                }
            } catch (Exception e) {
                Log.e(TAG, "Error processing PDF", e);
            }
        }

        scannerCallback.invoke(response);
        scannerCallback = null;
    }

    private boolean includePdf() {
        return scannerOptions != null
                && scannerOptions.hasKey("includePdf")
                && scannerOptions.getBoolean("includePdf");
    }

    /**
     * Copies the ML Kit PDF into the app cache directory so the URI stays
     * valid after the scanner activity is gone. Note: the PDF is built by
     * ML Kit at its own resolution — quality, maxWidth/maxHeight and EXIF
     * options do not apply to it.
     */
    private WritableMap processPdf(GmsDocumentScanningResult.Pdf pdf) throws IOException {
        Activity currentActivity = getCurrentActivity();
        if (currentActivity == null) {
            return null;
        }

        InputStream inputStream = currentActivity.getContentResolver().openInputStream(pdf.getUri());
        if (inputStream == null) {
            return null;
        }

        byte[] pdfBytes = readBytes(inputStream);
        inputStream.close();

        String fileName = UUID.randomUUID().toString() + ".pdf";
        File pdfFile = new File(currentActivity.getCacheDir(), fileName);

        FileOutputStream fileOutputStream = new FileOutputStream(pdfFile);
        fileOutputStream.write(pdfBytes);
        fileOutputStream.close();

        WritableMap pdfObject = new WritableNativeMap();
        pdfObject.putString("uri", Uri.fromFile(pdfFile).toString());
        pdfObject.putInt("pageCount", pdf.getPageCount());
        pdfObject.putInt("fileSize", pdfBytes.length);
        pdfObject.putString("fileName", fileName);
        pdfObject.putString("type", "application/pdf");
        return pdfObject;
    }

    private WritableMap processImage(Uri imageUri) throws IOException {
        WritableMap imageObject = new WritableNativeMap();

        Activity currentActivity = getCurrentActivity();
        if (currentActivity == null) {
            return null;
        }

        // Read the image
        InputStream inputStream = currentActivity.getContentResolver().openInputStream(imageUri);
        if (inputStream == null) {
            return null;
        }

        byte[] imageBytes = readBytes(inputStream);
        inputStream.close();

        // Decode bitmap to get dimensions
        android.graphics.BitmapFactory.Options options = new android.graphics.BitmapFactory.Options();
        options.inJustDecodeBounds = false;
        Bitmap bitmap = android.graphics.BitmapFactory.decodeByteArray(imageBytes, 0, imageBytes.length, options);

        if (bitmap == null) {
            return null;
        }

        // Cap the long edge if the caller supplied maxWidth / maxHeight.
        // Both are honored: the smaller scale factor wins so neither axis
        // exceeds its cap. Done BEFORE compress() so the encoded JPEG
        // carries the smaller dimensions + proportionally smaller bytes.
        double maxWidth = 0;
        double maxHeight = 0;
        if (scannerOptions != null && scannerOptions.hasKey("maxWidth")) {
            maxWidth = scannerOptions.getDouble("maxWidth");
        }
        if (scannerOptions != null && scannerOptions.hasKey("maxHeight")) {
            maxHeight = scannerOptions.getDouble("maxHeight");
        }
        bitmap = resizeBitmapIfNeeded(bitmap, maxWidth, maxHeight);

        // Apply quality compression if needed
        double quality = 1.0;
        if (scannerOptions != null && scannerOptions.hasKey("quality")) {
            quality = scannerOptions.getDouble("quality");
        }

        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        int qualityPercent = (int) (quality * 100);
        bitmap.compress(Bitmap.CompressFormat.JPEG, qualityPercent, outputStream);
        byte[] processedImageBytes = outputStream.toByteArray();
        outputStream.close();

        // Save to cache directory
        String fileName = UUID.randomUUID().toString() + ".jpg";
        File cacheDir = currentActivity.getCacheDir();
        File imageFile = new File(cacheDir, fileName);

        FileOutputStream fileOutputStream = new FileOutputStream(imageFile);
        fileOutputStream.write(processedImageBytes);
        fileOutputStream.close();

        boolean includeExif = scannerOptions != null && scannerOptions.hasKey("includeExif") && scannerOptions.getBoolean("includeExif");

        // Write EXIF data to the saved file
        WritableMap exifData = null;
        if (includeExif) {
            exifData = writeExifToFile(imageFile, bitmap.getWidth(), bitmap.getHeight());
        }

        // Re-read file size after EXIF write (EXIF modifies the file)
        long fileSize = imageFile.length();

        // Build response
        imageObject.putString("uri", Uri.fromFile(imageFile).toString());
        imageObject.putString("fileName", fileName);
        imageObject.putString("type", "image/jpeg");
        imageObject.putInt("width", bitmap.getWidth());
        imageObject.putInt("height", bitmap.getHeight());
        imageObject.putInt("fileSize", (int) fileSize);

        // Add base64 if requested (re-read if EXIF was written)
        if (scannerOptions != null && scannerOptions.hasKey("includeBase64") &&
            scannerOptions.getBoolean("includeBase64")) {
            if (includeExif) {
                // Re-read file since EXIF modified it
                InputStream rereadStream = new java.io.FileInputStream(imageFile);
                byte[] finalBytes = readBytes(rereadStream);
                rereadStream.close();
                String base64 = Base64.encodeToString(finalBytes, Base64.NO_WRAP);
                imageObject.putString("base64", base64);
            } else {
                String base64 = Base64.encodeToString(processedImageBytes, Base64.NO_WRAP);
                imageObject.putString("base64", base64);
            }
        }

        if (exifData != null) {
            imageObject.putMap("exif", exifData);
        }

        bitmap.recycle();

        return imageObject;
    }

    private WritableMap writeExifToFile(File imageFile, int width, int height) {
        WritableMap exifResponse = new WritableNativeMap();

        try {
            ExifInterface exif = new ExifInterface(imageFile.getAbsolutePath());

            // Timestamp
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy:MM:dd HH:mm:ss", Locale.US);
            String dateString = dateFormat.format(new Date());
            exif.setAttribute(ExifInterface.TAG_DATETIME, dateString);
            exif.setAttribute(ExifInterface.TAG_DATETIME_ORIGINAL, dateString);
            exif.setAttribute(ExifInterface.TAG_DATETIME_DIGITIZED, dateString);
            exifResponse.putString("DateTimeOriginal", dateString);
            exifResponse.putString("DateTimeDigitized", dateString);

            // Dimensions
            exif.setAttribute(ExifInterface.TAG_IMAGE_WIDTH, String.valueOf(width));
            exif.setAttribute(ExifInterface.TAG_IMAGE_LENGTH, String.valueOf(height));
            exifResponse.putInt("PixelXDimension", width);
            exifResponse.putInt("PixelYDimension", height);

            // Device info
            String make = Build.MANUFACTURER;
            String model = Build.MODEL;
            exif.setAttribute(ExifInterface.TAG_MAKE, make);
            exif.setAttribute(ExifInterface.TAG_MODEL, model);
            exifResponse.putString("Make", make);
            exifResponse.putString("Model", model);

            // Software
            String software = "DocumentScanner";
            try {
                android.content.pm.PackageInfo pInfo = reactContext.getPackageManager()
                        .getPackageInfo(reactContext.getPackageName(), 0);
                software = pInfo.packageName;
            } catch (Exception ignored) {}
            exif.setAttribute(ExifInterface.TAG_SOFTWARE, software);
            exifResponse.putString("Software", software);

            // Color space
            exif.setAttribute(ExifInterface.TAG_COLOR_SPACE, String.valueOf(ExifInterface.COLOR_SPACE_S_RGB));
            exifResponse.putInt("ColorSpace", 1);

            // GPS data
            if (currentLocation != null) {
                exif.setGpsInfo(currentLocation);

                exifResponse.putDouble("GPSLatitude", currentLocation.getLatitude());
                exifResponse.putDouble("GPSLongitude", currentLocation.getLongitude());
                exifResponse.putDouble("GPSAltitude", currentLocation.getAltitude());
                exifResponse.putDouble("GPSHorizontalAccuracy", currentLocation.getAccuracy());

                SimpleDateFormat utcFormat = new SimpleDateFormat("yyyy:MM:dd HH:mm:ss", Locale.US);
                utcFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
                exifResponse.putString("GPSDateTimeUTC", utcFormat.format(new Date(currentLocation.getTime())));
            }

            exif.saveAttributes();
        } catch (IOException e) {
            Log.e(TAG, "Error writing EXIF data", e);
        }

        return exifResponse;
    }

    private byte[] readBytes(InputStream inputStream) throws IOException {
        ByteArrayOutputStream byteBuffer = new ByteArrayOutputStream();
        byte[] buffer = new byte[16384];
        int len;
        while ((len = inputStream.read(buffer)) != -1) {
            byteBuffer.write(buffer, 0, len);
        }
        return byteBuffer.toByteArray();
    }

    /**
     * Cap the long edge of the bitmap at maxWidth × maxHeight (both
     * applied; smaller scale factor wins so neither axis exceeds its
     * cap). Returns the input unchanged when either cap is zero/missing
     * or when the bitmap is already within bounds. Aspect ratio
     * preserved. Recycles the original bitmap when a resized copy is
     * produced — the caller MUST NOT keep a reference to the original
     * after this call.
     */
    private Bitmap resizeBitmapIfNeeded(Bitmap bitmap, double maxWidth, double maxHeight) {
        if (maxWidth <= 0 || maxHeight <= 0) return bitmap;
        int width = bitmap.getWidth();
        int height = bitmap.getHeight();
        if (width <= maxWidth && height <= maxHeight) return bitmap;
        double scale = Math.min(maxWidth / (double) width, maxHeight / (double) height);
        int newWidth = (int) Math.floor(width * scale);
        int newHeight = (int) Math.floor(height * scale);
        Bitmap resized = Bitmap.createScaledBitmap(bitmap, newWidth, newHeight, true);
        if (resized != bitmap) {
            bitmap.recycle();
        }
        return resized;
    }
}
